version: '3'
services:
  
  app:
    build: .
    container_name: cons-node
    env_file: .env
    environment:
      - DB_HOST=mysql_db
      - DB_DIALECT=mysql
      - DB_NAME=db_food
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=1234 
    ports:
      - "80:8080"
    networks:
      - node-network

networks:
  node-network: